### ISSUE TITLE
字典生成思路

### ISSUE THREAD

**Issue by helloyw** [ffffffff0x/name-fuzz#1]
师傅，项目（name-fuzz）是根据人员名称中文来进行生成具体内容，可不可以以拼音的方式进行生成例如输入zhangsan生成zs、zhangs这种呢。

**Comment by No-Github** [comment]
应该可以实现，我找一找方案👌

**Comment by No-Github** [comment]
已支持

![image](https://user-images.githubusercontent.com/18167071/152482765-3b6286da-3134-4524-a408-84ec46cd6104.png)

**Comment by helloyw** [comment]
能否再加个规则例如：wangfugui wfgui 取两面两个首字母保留最后一个拼音。

**Comment by helloyw** [comment]
能否再加个规则例如：wangfugui wfgui 取两面两个首字母保留最后一个拼音。

**Comment by No-Github** [comment]
已添加

<img width="505" alt="image" src="https://user-images.githubusercontent.com/18167071/188385413-15c9cfbb-082e-4615-a01e-6e24960e7a98.png">

---

<img width="414" alt="image" src="https://user-images.githubusercontent.com/18167071/188385447-27ef9fee-bbdf-4fc4-9093-e3639d33698c.png">

**Comment by helloyw** [comment]
https://www.yuque.com/pmiaowu/bomi9w/ougg6d 还有这个

**Comment by No-Github** [comment]
已添加

<img width="401" alt="image" src="https://user-images.githubusercontent.com/18167071/188422349-713ba0fc-49bf-4286-9211-b6b0dff76b91.png">

---

<img width="417" alt="image" src="https://user-images.githubusercontent.com/18167071/188422400-38febc9d-caf3-42ed-9cde-4ae06052032e.png">

**Comment by helloyw** [comment]
感谢！
