### ISSUE TITLE
基于实战的建议

### ISSUE THREAD

**Issue by T4y1oR** [ffffffff0x/name-fuzz#2]
例如：百度
建议添加首字母大写：Baidu

Baidu123
Baidu@123

**Comment by No-Github** [comment]
可以，我之后添加一下

**Comment by No-Github** [comment]
已支持
<img width="507" alt="image" src="https://user-images.githubusercontent.com/18167071/162566458-e291e221-2072-480d-a05b-63e1241692c0.png">

**Comment by No-Github** [comment]
如果没有其他的问题或需求，这个issue就先关闭了哈
